import type { Company, Contact, Lead, Activity } from '../../types';

export const DEMO_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    legalName: 'Expresso Rodoviário Silva Ltda',
    tradeName: 'Rodoviário Silva',
    cnpj: '12345678000199',
    segment: 'Transporte & Logística',
    size: 'Média',
    employeeCount: 240,
    estimatedRevenue: 15000000,
    website: 'https://rodoviariosilva.com.br',
    linkedin: 'https://linkedin.com/company/rodoviariosilva',
    phones: ['(11) 3456-7890'],
    emails: ['contato@rodoviariosilva.com.br'],
    address: 'Av. das Indústrias, 1000',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01000-000',
    owner: 'Marcelo Nascimento',
    status: 'Ativo',
    tags: ['Frotista', 'Logística'],
    observations: 'Operação dedicada a transporte de cargas fracionadas.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-2',
    legalName: 'TransLogística Alfa Brasil S.A.',
    tradeName: 'Alfa Logística',
    cnpj: '98765432000188',
    segment: 'Cargas Refrigeradas',
    size: 'Grande',
    employeeCount: 520,
    estimatedRevenue: 45000000,
    website: 'https://alfalogistica.com.br',
    linkedin: 'https://linkedin.com/company/alfalogistica',
    phones: ['(19) 3211-9900'],
    emails: ['comercial@alfalogistica.com.br'],
    address: 'Rodovia Anhanguera, Km 98',
    city: 'Campinas',
    state: 'SP',
    zipCode: '13000-000',
    owner: 'João Reis',
    status: 'Ativo',
    tags: ['Refrigerado', 'Enterprise'],
    observations: 'Necessita de rastreamento avançado e prevenção de sinistros.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-3',
    legalName: 'TransNacional Frotas & Cargas S.A.',
    tradeName: 'TransNacional Frotas',
    cnpj: '55443322000177',
    segment: 'Transporte de Medicamentos',
    size: 'Grande',
    employeeCount: 800,
    estimatedRevenue: 90000000,
    website: 'https://transnacionalfrotas.com.br',
    linkedin: 'https://linkedin.com/company/transnacionalfrotas',
    phones: ['(41) 3344-5566'],
    emails: ['contato@transnacionalfrotas.com.br'],
    address: 'Av. das Araucárias, 500',
    city: 'Curitiba',
    state: 'PR',
    zipCode: '80000-000',
    owner: 'Marcelo Nascimento',
    status: 'Ativo',
    tags: ['Farma', 'Alta Qualificação'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-4',
    legalName: 'SulLog Operadora Logística Ltda',
    tradeName: 'SulLog Transportes',
    cnpj: '11223344000166',
    segment: 'Agronegócio & Cargas Granel',
    size: 'Média',
    employeeCount: 180,
    estimatedRevenue: 28000000,
    website: 'https://sullog.com.br',
    linkedin: 'https://linkedin.com/company/sullog',
    phones: ['(51) 3233-4455'],
    emails: ['operacoes@sullog.com.br'],
    address: 'Av. Sertório, 2400',
    city: 'Porto Alegre',
    state: 'RS',
    zipCode: '90000-000',
    owner: 'João Reis',
    status: 'Ativo',
    tags: ['Agro', 'Frota Própria'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-5',
    legalName: 'Global Cargo & Distribuição Ltda',
    tradeName: 'Global Cargo',
    cnpj: '66778899000155',
    segment: 'Distribuição Urbana & E-commerce',
    size: 'Grande',
    employeeCount: 650,
    estimatedRevenue: 60000000,
    website: 'https://globalcargo.com.br',
    linkedin: 'https://linkedin.com/company/globalcargo',
    phones: ['(47) 3455-6677'],
    emails: ['contato@globalcargo.com.br'],
    address: 'Rua das Palmeiras, 150',
    city: 'Joinville',
    state: 'SC',
    zipCode: '89200-000',
    owner: 'Marcelo Nascimento',
    status: 'Ativo',
    tags: ['E-commerce', 'Last Mile'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-6',
    legalName: 'Rápido Litoral Express Transporte Eireli',
    tradeName: 'Litoral Express',
    cnpj: '77889900000144',
    segment: 'Cargas Expressas',
    size: 'Pequena',
    employeeCount: 85,
    estimatedRevenue: 8500000,
    website: 'https://litoralexpress.com.br',
    linkedin: 'https://linkedin.com/company/litoralexpress',
    phones: ['(21) 2566-7788'],
    emails: ['atendimento@litoralexpress.com.br'],
    address: 'Av. Brasil, 4500',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '20000-000',
    owner: 'João Reis',
    status: 'Ativo',
    tags: ['Express', 'Frota Agregada'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-7',
    legalName: 'Mega Frotas Brasil Soluções Logísticas S.A.',
    tradeName: 'Mega Frotas Brasil',
    cnpj: '88990011000133',
    segment: 'Transporte Rodoviário Pesado',
    size: 'Grande',
    employeeCount: 1200,
    estimatedRevenue: 140000000,
    website: 'https://megafrotasbrasil.com.br',
    linkedin: 'https://linkedin.com/company/megafrotasbrasil',
    phones: ['(65) 3688-9900'],
    emails: ['diretoria@megafrotasbrasil.com.br'],
    address: 'Rodovia dos Imigrantes, Km 12',
    city: 'Cuiabá',
    state: 'MT',
    zipCode: '78000-000',
    owner: 'Marcelo Nascimento',
    status: 'Ativo',
    tags: ['Frota Pesada', 'Grãos'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEMO_CONTACTS: Contact[] = [
  {
    id: 'cont-1',
    name: 'Roberto Silva',
    role: 'Diretor de Operações',
    department: 'Operações',
    phone: '(11) 98765-4321',
    whatsapp: '(11) 98765-4321',
    email: 'roberto.silva@rodoviariosilva.com.br',
    linkedin: 'https://linkedin.com/in/robertosilva',
    status: 'Ativo',
    companyId: 'comp-1',
    company: DEMO_COMPANIES[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont-2',
    name: 'Ana Paula Souza',
    role: 'Gerente de Logística & Frotas',
    department: 'Logística',
    phone: '(19) 99876-5432',
    whatsapp: '(19) 99876-5432',
    email: 'ana.souza@alfalogistica.com.br',
    linkedin: 'https://linkedin.com/in/anapaulasouza',
    status: 'Ativo',
    companyId: 'comp-2',
    company: DEMO_COMPANIES[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont-3',
    name: 'Juliana Mendes',
    role: 'Gerente de Gestão de Risco',
    department: 'Gerenciamento de Risco',
    phone: '(41) 98877-6655',
    whatsapp: '(41) 98877-6655',
    email: 'juliana.mendes@transnacionalfrotas.com.br',
    linkedin: 'https://linkedin.com/in/julianamendes',
    status: 'Ativo',
    companyId: 'comp-3',
    company: DEMO_COMPANIES[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont-4',
    name: 'Marcelo Oliveira',
    role: 'VP de Operações Logísticas',
    department: 'Diretoria',
    phone: '(51) 97766-5544',
    whatsapp: '(51) 97766-5544',
    email: 'marcelo.oliveira@sullog.com.br',
    linkedin: 'https://linkedin.com/in/marcelooliveira',
    status: 'Ativo',
    companyId: 'comp-4',
    company: DEMO_COMPANIES[3],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont-5',
    name: 'Patricia Costa',
    role: 'Gerente de Compras & Suprimentos',
    department: 'Suprimentos',
    phone: '(47) 96655-4433',
    whatsapp: '(47) 96655-4433',
    email: 'patricia.costa@globalcargo.com.br',
    linkedin: 'https://linkedin.com/in/patriciacosta',
    status: 'Ativo',
    companyId: 'comp-5',
    company: DEMO_COMPANIES[4],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont-6',
    name: 'Ricardo Santos',
    role: 'Gerente Geral',
    department: 'Gestão',
    phone: '(21) 95544-3322',
    whatsapp: '(21) 95544-3322',
    email: 'ricardo.santos@litoralexpress.com.br',
    linkedin: 'https://linkedin.com/in/ricardosantos',
    status: 'Ativo',
    companyId: 'comp-6',
    company: DEMO_COMPANIES[5],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont-7',
    name: 'Eduardo Fonseca',
    role: 'CEO / Diretor Presidente',
    department: 'Diretoria Executiva',
    phone: '(65) 94433-2211',
    whatsapp: '(65) 94433-2211',
    email: 'eduardo.fonseca@megafrotasbrasil.com.br',
    linkedin: 'https://linkedin.com/in/eduardofonseca',
    status: 'Ativo',
    companyId: 'comp-7',
    company: DEMO_COMPANIES[6],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEMO_LEADS: Lead[] = [
  {
    id: 'lead-1',
    status: 'Novo Lead',
    source: 'Prospecção Ativa',
    channel: 'Outbound',
    temperature: 'Morno',
    score: 85,
    owner: 'Marcelo Nascimento',
    pic: 'PIC1_Expansao',
    companyId: 'comp-1',
    company: DEMO_COMPANIES[0],
    contactId: 'cont-1',
    contact: DEMO_CONTACTS[0],
    qualification: {
      segmentoOperacao: 'Cargas Fracionadas',
      tipoCarga: 'Geral',
      frotaPropria: '60 veículos',
      frotaTerceiros: '40 agregados',
      dorPrincipal: 'Alto índice de sinistros e falta de telemetria integrada',
      solucaoAtlas: 'GR',
      nivelAutoridade: 'Decisor',
      interessePercebido: 'Alto',
      horizonteDecisao: '30 dias',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-2',
    status: 'Qualificação',
    source: 'Outbound Apollo',
    channel: 'LinkedIn',
    temperature: 'Quente',
    score: 92,
    owner: 'João Reis',
    pic: 'PIC2_Risco',
    companyId: 'comp-2',
    company: DEMO_COMPANIES[1],
    contactId: 'cont-2',
    contact: DEMO_CONTACTS[1],
    qualification: {
      segmentoOperacao: 'Cargas Refrigeradas',
      tipoCarga: 'Perecíveis / Alimentos',
      frotaPropria: '120 caminhões refrigerados',
      dorPrincipal: 'Custo elevado de apólice de seguro por conta de roubos',
      solucaoAtlas: 'GR',
      nivelAutoridade: 'Influenciador',
      interessePercebido: 'Alto',
      horizonteDecisao: 'Imediato',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-3',
    status: 'Primeiro Contato',
    source: 'Indicação',
    channel: 'WhatsApp',
    temperature: 'Quente',
    score: 95,
    owner: 'Marcelo Nascimento',
    pic: 'PIC1_Expansao',
    companyId: 'comp-3',
    company: DEMO_COMPANIES[2],
    contactId: 'cont-3',
    contact: DEMO_CONTACTS[2],
    qualification: {
      segmentoOperacao: 'Medicamentos & Química',
      tipoCarga: 'Alto Valor Agregado',
      frotaPropria: '200 veículos',
      dorPrincipal: 'Exigência de compliance farmacêutico ANVISA e rastreabilidade 24/7',
      solucaoAtlas: 'Profile',
      nivelAutoridade: 'Decisor',
      interessePercebido: 'Alto',
      horizonteDecisao: '30 dias',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-4',
    status: 'Diagnóstico',
    source: 'Prospecção Ativa',
    channel: 'Cold Calling',
    temperature: 'Morno',
    score: 88,
    owner: 'João Reis',
    pic: 'PIC3_Transicao',
    companyId: 'comp-4',
    company: DEMO_COMPANIES[3],
    contactId: 'cont-4',
    contact: DEMO_CONTACTS[3],
    qualification: {
      segmentoOperacao: 'Grãos & Agro',
      tipoCarga: 'Granel',
      frotaPropria: '80 bitrens',
      dorPrincipal: 'Dificuldade de cadastro e consulta ágil de motoristas terceiros em safra',
      solucaoAtlas: 'Connect',
      nivelAutoridade: 'Decisor',
      interessePercebido: 'Médio',
      horizonteDecisao: '60-90 dias',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-5',
    status: 'Proposta',
    source: 'Inbound Site',
    channel: 'Web',
    temperature: 'Quente',
    score: 89,
    owner: 'Marcelo Nascimento',
    pic: 'PIC1_Expansao',
    companyId: 'comp-5',
    company: DEMO_COMPANIES[4],
    contactId: 'cont-5',
    contact: DEMO_CONTACTS[4],
    qualification: {
      segmentoOperacao: 'E-commerce & Last Mile',
      tipoCarga: 'Pacotes / Encomendas',
      frotaPropria: '150 vans e VUCs',
      dorPrincipal: 'Demora na aprovação de motoristas agregados aumentando tempo de pátio',
      solucaoAtlas: 'Profile',
      nivelAutoridade: 'Decisor',
      interessePercebido: 'Alto',
      horizonteDecisao: 'Imediato',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-6',
    status: 'Negociação',
    source: 'Bitrix24',
    channel: 'Telefone',
    temperature: 'Quente',
    score: 94,
    owner: 'João Reis',
    pic: 'PIC2_Risco',
    companyId: 'comp-6',
    company: DEMO_COMPANIES[5],
    contactId: 'cont-6',
    contact: DEMO_CONTACTS[5],
    qualification: {
      segmentoOperacao: 'Expressa',
      tipoCarga: 'Carga Leve',
      frotaPropria: '45 utilitários',
      dorPrincipal: 'Revisão das regras de GR com seguradora parceira',
      solucaoAtlas: 'GR',
      nivelAutoridade: 'Decisor',
      interessePercebido: 'Alto',
      horizonteDecisao: 'Imediato',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-7',
    status: 'Fechado Ganho',
    source: 'Evento Logística',
    channel: 'Evento',
    temperature: 'Quente',
    score: 98,
    owner: 'Marcelo Nascimento',
    pic: 'PIC1_Expansao',
    companyId: 'comp-7',
    company: DEMO_COMPANIES[6],
    contactId: 'cont-7',
    contact: DEMO_CONTACTS[6],
    qualification: {
      segmentoOperacao: 'Cargas Pesadas',
      tipoCarga: 'Maquinário / Agro',
      frotaPropria: '400 carretas',
      dorPrincipal: 'Integração completa de cadastro, sinistros e central de risco unificada',
      solucaoAtlas: 'Combinação',
      nivelAutoridade: 'Decisor',
      interessePercebido: 'Alto',
      horizonteDecisao: 'Imediato',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEMO_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    type: 'Reunião',
    owner: 'Marcelo Nascimento',
    date: new Date(Date.now() + 86400000).toISOString(),
    time: '14:00',
    status: 'Pendente',
    observations: 'Apresentação da plataforma de Gestão de Risco AtlasGR',
    leadId: 'lead-1',
    lead: DEMO_LEADS[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act-2',
    type: 'Ligação',
    owner: 'João Reis',
    date: new Date().toISOString(),
    time: '10:30',
    status: 'Em andamento',
    observations: 'Alinhamento sobre apólice de seguro e exigências da gerenciadora',
    leadId: 'lead-2',
    lead: DEMO_LEADS[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act-3',
    type: 'Follow-up',
    owner: 'Marcelo Nascimento',
    date: new Date(Date.now() + 172800000).toISOString(),
    time: '16:00',
    status: 'Pendente',
    observations: 'Enviar proposta comercial atualizada com desconto por frota',
    leadId: 'lead-5',
    lead: DEMO_LEADS[4],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
