[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Parameter(Mandatory = $false)]
    [string]$ProjectRoot = ".",

    [Parameter(Mandatory = $false)]
    [switch]$Rollback,

    [Parameter(Mandatory = $false)]
    [switch]$RunValidation,

    [Parameter(Mandatory = $false)]
    [switch]$SkipHtmlReport
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Clear-Host

$Script:PhaseName = 'FASE 12 — API LAYER'
$Script:PhaseCode = 'phase-12'
$Script:Version = '1.0.0'
$Script:StartedAt = Get-Date
$Script:CreatedFiles = New-Object System.Collections.Generic.List[string]
$Script:UpdatedFiles = New-Object System.Collections.Generic.List[string]
$Script:CreatedDirectories = New-Object System.Collections.Generic.List[string]
$Script:Warnings = New-Object System.Collections.Generic.List[string]
$Script:ValidationFindings = New-Object System.Collections.Generic.List[string]
$Script:Hashes = @{}
$Script:ManifestFile = $null
$Script:ReportFile = $null

function Write-Header {
    Write-Host '===================================================='
    Write-Host ' PROSPECTOR-ATLAS — FASE 12 — API LAYER ENTERPRISE '
    Write-Host '===================================================='
    Write-Host ("Version : {0}" -f $Script:Version)
    Write-Host ("Started : {0}" -f $Script:StartedAt.ToString('yyyy-MM-dd HH:mm:ss'))
    Write-Host ''
}

function Write-Log {
    param(
        [Parameter(Mandatory = $true)][string]$Level,
        [Parameter(Mandatory = $true)][string]$Message
    )
    $timestamp = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
    $line = "[$timestamp] [$Level] $Message"
    switch ($Level) {
        'ERROR' { Write-Host $line -ForegroundColor Red }
        'WARN'  { Write-Host $line -ForegroundColor Yellow }
        'OK'    { Write-Host $line -ForegroundColor Green }
        default { Write-Host $line }
    }
}

function Resolve-AbsolutePath {
    param([Parameter(Mandatory = $true)][string]$BasePath)
    $resolved = Resolve-Path -LiteralPath $BasePath -ErrorAction SilentlyContinue
    if ($null -ne $resolved) { return $resolved.Path }
    return [System.IO.Path]::GetFullPath($BasePath)
}

function Write-Folder {
    param([Parameter(Mandatory = $true)][string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        if ($PSCmdlet.ShouldProcess($Path, 'Create directory')) {
            New-Item -ItemType Directory -Path $Path -Force | Out-Null
        }
        $Script:CreatedDirectories.Add($Path)
        Write-Log -Level 'OK' -Message ("Directory ready: {0}" -f $Path)
    }
}

function Write-FileFromContent {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )

    $directory = Split-Path -Parent $Path
    if (-not [string]::IsNullOrWhiteSpace($directory)) {
        Write-Folder -Path $directory
    }

    $exists = Test-Path -LiteralPath $Path
    $write = $true
    if ($exists) {
        $previous = [System.IO.File]::ReadAllText($Path)
        if ($previous -eq $Content) {
            $write = $false
        }
    }

    if ($write) {
        if ($PSCmdlet.ShouldProcess($Path, 'Write file')) {
            [System.IO.File]::WriteAllText($Path, $Content, (New-Object System.Text.UTF8Encoding($false)))
        }
        if ($exists) { $Script:UpdatedFiles.Add($Path) } else { $Script:CreatedFiles.Add($Path) }
        Write-Log -Level 'OK' -Message ("File written: {0}" -f $Path)
    }
}

function Get-EnterpriseTsHeader {
@'
/**
 * PROSPECTOR-ATLAS
 * Enterprise API Layer
 * Generated by FASE-12-API.ps1
 * Clean Architecture | DDD | Hexagonal | CQRS | REST | OpenAPI 3.1
 */
'@
}

function New-TsFileContent {
    param(
        [Parameter(Mandatory = $true)][string]$Namespace,
        [Parameter(Mandatory = $true)][string]$ClassName,
        [Parameter(Mandatory = $true)][string]$Kind
    )
$header = Get-EnterpriseTsHeader
@"
$header
export interface ${ClassName}Payload {
    readonly id: string;
    readonly name: string;
    readonly timestamp: string;
    readonly metadata: Readonly<Record<string, string>>;
}

/**
 * ${ClassName}
 * Enterprise ${Kind} implementation for ${Namespace}.
 */
export class ${ClassName} {
    public readonly kind: string;
    public readonly namespace: string;

    public constructor() {
        this.kind = '${Kind}';
        this.namespace = '${Namespace}';
    }

    public describe(): string {
        return `${ClassName}::${Kind}::${Namespace}`;
    }

    public execute(payload: ${ClassName}Payload): Readonly<${ClassName}Payload> {
        return {
            id: payload.id,
            name: payload.name,
            timestamp: payload.timestamp,
            metadata: payload.metadata
        };
    }
}
"@
}

function New-IndexContent {
    param([Parameter(Mandatory = $true)][string[]]$Exports)
    $lines = @((Get-EnterpriseTsHeader).TrimEnd())
    foreach ($item in $Exports) {
        $lines += "export * from './$item';"
    }
    ($lines -join "`r`n") + "`r`n"
}

function Get-ApiStructure {
    $root = 'src/api'
    [ordered]@{
        'controllers' = @(
            'LeadController','CompanyController','ContactController',
            'OpportunityController','TaskController','MeetingController',
            'ProposalController','PipelineController','CampaignController',
            'ActivityController','DashboardController','ReportController',
            'NotificationController','HealthController','SystemController',
            'UserController','OrganizationController','AuthenticationController',
            'AuthorizationController','AuditController'
        );
        'routes' = @(
            'lead.routes','company.routes','contact.routes',
            'opportunity.routes','task.routes','meeting.routes',
            'proposal.routes','pipeline.routes','campaign.routes',
            'activity.routes','dashboard.routes','report.routes',
            'notification.routes','health.routes','system.routes',
            'auth.routes','organization.routes','user.routes',
            'audit.routes'
        );
        'middlewares' = @(
            'AuthenticationMiddleware','AuthorizationMiddleware',
            'ErrorHandlerMiddleware','RequestLoggerMiddleware',
            'CorrelationIdMiddleware','CompressionMiddleware',
            'CorsMiddleware','HelmetMiddleware','BodyParserMiddleware',
            'ValidationMiddleware','PaginationMiddleware','TenantMiddleware',
            'LocaleMiddleware','RequestContextMiddleware','TimeoutMiddleware'
        );
        'validators' = @(
            'LeadRequestValidator','CompanyRequestValidator','ContactRequestValidator',
            'OpportunityRequestValidator','TaskRequestValidator','MeetingRequestValidator',
            'ProposalRequestValidator','AuthenticationValidator','PaginationValidator'
        );
        'requests' = @(
            'CreateLeadRequest','UpdateLeadRequest','CreateCompanyRequest',
            'CreateContactRequest','CreateOpportunityRequest','CreateTaskRequest',
            'CreateMeetingRequest','SearchRequest','PaginationRequest','SortRequest'
        );
        'responses' = @(
            'ApiResponse','SuccessResponse','ErrorResponse','ValidationResponse',
            'PaginatedResponse','LeadResponse','CompanyResponse','ContactResponse',
            'OpportunityResponse','TaskResponse','MeetingResponse','ProposalResponse',
            'DashboardResponse'
        );
        'serializers' = @('JsonSerializer','CsvSerializer','XmlSerializer','PdfSerializer');
        'presenters' = @(
            'LeadPresenter','CompanyPresenter','ContactPresenter',
            'OpportunityPresenter','TaskPresenter','ProposalPresenter',
            'DashboardPresenter'
        );
        'transformers' = @(
            'LeadTransformer','CompanyTransformer','ContactTransformer',
            'OpportunityTransformer','TaskTransformer','ProposalTransformer'
        );
        'filters' = @('ExceptionFilter','ValidationFilter','AuthorizationFilter','RateLimitFilter');
        'versioning' = @('ApiVersion','VersionResolver','VersionMiddleware');
        'openapi' = @('OpenApiBuilder','OpenApiGenerator','OpenApiSchemas','OpenApiResponses','OpenApiSecurity');
        'swagger' = @('SwaggerConfiguration','SwaggerBuilder','SwaggerRoutes');
        'documentation' = @('ApiDocumentation','EndpointCatalog','ApiExamples');
        'rate-limit' = @('RateLimiter','MemoryRateLimiter','RedisRateLimiter','ThrottlePolicy');
        'security' = @('SecurityHeaders','HelmetConfiguration','CsrfProtection','InputSanitizer','OutputSanitizer');
        'cors' = @('CorsPolicy');
        'compression' = @('CompressionPolicy');
        'health' = @('HealthCheck','ReadinessCheck','LivenessCheck','DependencyHealth');
        'metrics' = @('ApiMetrics','RequestMetrics','EndpointMetrics');
        'errors' = @('ApiError','ValidationError','UnauthorizedError','ForbiddenError','ConflictError','NotFoundError');
        'exceptions' = @('ApiException','BusinessException','InfrastructureException');
        'hooks' = @('BeforeRequestHook','AfterRequestHook','BeforeResponseHook');
        'interceptors' = @(
            'RequestInterceptor','ResponseInterceptor','LoggingInterceptor',
            'TracingInterceptor','MetricsInterceptor'
        );
        'pipeline' = @('RequestPipeline','MiddlewarePipeline');
        'config' = @('ApiConfiguration','CorsConfiguration','SecurityConfiguration','SwaggerConfiguration');
        'bootstrap' = @('Bootstrap','ServerBootstrap','ApiBootstrap');
        'server' = @('Server','ExpressServer','FastifyServer','Application');
    }
}

function Write-ApiFiles {
    param([Parameter(Mandatory = $true)][string]$TargetRoot)

    $structure = Get-ApiStructure
    foreach ($segment in $structure.Keys) {
        $folder = Join-Path $TargetRoot (Join-Path 'src/api' $segment)
        Write-Folder -Path $folder
        $exports = New-Object System.Collections.Generic.List[string]
        foreach ($name in $structure[$segment]) {
            $filename = "$name.ts"
            $path = Join-Path $folder $filename
            $kind = if ($segment -eq 'routes') { 'RouteModule' } else { 'Component' }
            $content = New-TsFileContent -Namespace $segment -ClassName ($name -replace '\.','_') -Kind $kind
            Write-FileFromContent -Path $path -Content $content
            $exports.Add($name)
        }
        $indexPath = Join-Path $folder 'index.ts'
        Write-FileFromContent -Path $indexPath -Content (New-IndexContent -Exports $exports.ToArray())
    }

    $apiRoot = Join-Path $TargetRoot 'src/api'
    Write-FileFromContent -Path (Join-Path $apiRoot 'index.ts') -Content @"
$(Get-EnterpriseTsHeader)
export * from './controllers';
export * from './routes';
export * from './middlewares';
export * from './validators';
export * from './requests';
export * from './responses';
export * from './serializers';
export * from './presenters';
export * from './transformers';
export * from './filters';
export * from './versioning';
export * from './openapi';
export * from './swagger';
export * from './documentation';
export * from './rate-limit';
export * from './security';
export * from './cors';
export * from './compression';
export * from './health';
export * from './metrics';
export * from './errors';
export * from './exceptions';
export * from './hooks';
export * from './interceptors';
export * from './pipeline';
export * from './config';
export * from './bootstrap';
export * from './server';
"@
}

function Get-DirectoryTree {
    param([Parameter(Mandatory = $true)][string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { return '' }
    $items = Get-ChildItem -LiteralPath $Path -Recurse | Sort-Object FullName
    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($item in $items) {
        $lines.Add($item.FullName.Substring($Path.Length).TrimStart('\'))
    }
    $lines -join "`n"
}

function Test-GeneratedFiles {
    param([Parameter(Mandatory = $true)][string]$TargetRoot)
    $apiRoot = Join-Path $TargetRoot 'src/api'
    if (-not (Test-Path -LiteralPath $apiRoot)) {
        $Script:ValidationFindings.Add('API root not found.')
        return
    }
    $files = Get-ChildItem -LiteralPath $apiRoot -Recurse -File
    $nameMap = @{}
    foreach ($file in $files) {
        if ($file.Length -le 0) {
            $Script:ValidationFindings.Add("Empty file: $($file.FullName)")
        }
        $content = [System.IO.File]::ReadAllText($file.FullName)
        if ($content -notmatch 'export ') {
            $Script:ValidationFindings.Add("Export not found: $($file.FullName)")
        }
        if ($content -match 'TODO|FIXME|placeholder|any\b') {
            $Script:ValidationFindings.Add("Forbidden token found: $($file.FullName)")
        }
        $lower = $file.Name.ToLowerInvariant()
        if ($nameMap.ContainsKey($lower)) {
            $Script:ValidationFindings.Add("Duplicate file name detected: $($file.Name)")
        } else {
            $nameMap[$lower] = $true
        }
        $hash = Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256
        $Script:Hashes[$file.FullName] = $hash.Hash
    }
}

function Invoke-ExternalValidation {
    param([Parameter(Mandatory = $true)][string]$TargetRoot)
    $commands = @(
        @{ Name = 'npm run lint';        Command = 'npm run lint' },
        @{ Name = 'npx tsc --noEmit';    Command = 'npx tsc --noEmit' },
        @{ Name = 'npm test';           Command = 'npm test' }
    )
    $results = New-Object System.Collections.Generic.List[object]
    foreach ($item in $commands) {
        $start = Get-Date
        try {
            Push-Location $TargetRoot
            $output = & cmd /c $item.Command 2>&1
            $code = $LASTEXITCODE
            Pop-Location
        } catch {
            if ((Get-Location).Path -ne $PWD.Path) { Pop-Location }
            $output = $_.Exception.Message
            $code = 1
        }
        $elapsed = ((Get-Date) - $start).TotalSeconds
        $results.Add([pscustomobject]@{
            Name            = $item.Name
            ExitCode        = $code
            DurationSeconds = [Math]::Round($elapsed, 2)
            Output          = [string]::Join("`n", $output)
        })
    }
    $results
}

function Write-Manifest {
    param(
        [Parameter(Mandatory = $true)][string]$TargetRoot,
        [Parameter(Mandatory = $true)][AllowEmptyCollection()][object[]]$ToolResults
    )
    $duration = ((Get-Date) - $Script:StartedAt).TotalSeconds
    $manifestPath = Join-Path $TargetRoot 'phase-12-manifest.json'
    $payload = [ordered]@{
        fase              = $Script:PhaseCode
        versao            = $Script:Version
        timestamp         = (Get-Date).ToString('o')
        duracaoSegundos   = [Math]::Round($duration, 2)
        arquivosCriados   = @($Script:CreatedFiles)
        arquivosAtualizados = @($Script:UpdatedFiles)
        diretoriosCriados = @($Script:CreatedDirectories)
        hashes            = $Script:Hashes
        estatisticas      = [ordered]@{
            totalArquivosCriados     = $Script:CreatedFiles.Count
            totalArquivosAtualizados = $Script:UpdatedFiles.Count
            totalDiretoriosCriados   = $Script:CreatedDirectories.Count
            totalValidacoes          = $Script:ValidationFindings.Count
        }
        ferramentas       = $ToolResults
    }
    $json = $payload | ConvertTo-Json -Depth 10
    Write-FileFromContent -Path $manifestPath -Content $json
    $Script:ManifestFile = $manifestPath
}

function Write-HtmlReport {
    param(
        [Parameter(Mandatory = $true)][string]$TargetRoot,
        [Parameter(Mandatory = $true)][AllowEmptyCollection()][object[]]$ToolResults
    )
    $status = if ($Script:ValidationFindings.Count -gt 0) { 'WARNING' } else { 'SUCCESS' }
    $duration = [Math]::Round(((Get-Date) - $Script:StartedAt).TotalSeconds, 2)
    $tree = Get-DirectoryTree -Path (Join-Path $TargetRoot 'src/api')
    $validationHtml = ($Script:ValidationFindings | ForEach-Object { "<li>$([System.Web.HttpUtility]::HtmlEncode($_))</li>" }) -join ''
    if ([string]::IsNullOrWhiteSpace($validationHtml)) { $validationHtml = '<li>No findings.</li>' }
    $hashHtml = ($Script:Hashes.GetEnumerator() | Sort-Object Name | ForEach-Object {
        "<tr><td>$([System.Web.HttpUtility]::HtmlEncode($_.Key))</td><td><code>$([System.Web.HttpUtility]::HtmlEncode($_.Value))</code></td></tr>"
    }) -join ''
    $toolHtml = ($ToolResults | ForEach-Object {
        "<article class='card'><h3>$($_.Name)</h3><p>Exit code: $($_.ExitCode)</p><p>Duration: $($_.DurationSeconds)s</p><pre>$([System.Web.HttpUtility]::HtmlEncode($_.Output))</pre></article>"
    }) -join ''
    $reportPath = Join-Path $TargetRoot 'FASE-12-REPORT.html'
    $html = @"
<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='utf-8' />
<meta name='viewport' content='width=device-width, initial-scale=1' />
<title>FASE 12 REPORT</title>
<style>
body{font-family:Segoe UI,Arial,sans-serif;background:#0b1020;color:#e8eefc;margin:0;padding:0;}
header{padding:32px;background:linear-gradient(135deg,#101935,#16315e);}
main{padding:24px;display:grid;gap:24px;}
section{background:#121a2f;border:1px solid #2e406d;border-radius:16px;padding:20px;}
h1,h2,h3{margin:0 0 12px;}
table{width:100%;border-collapse:collapse;}
td,th{border:1px solid #2e406d;padding:8px;text-align:left;vertical-align:top;}
code,pre{white-space:pre-wrap;word-break:break-word;}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;}
.card{background:#0f1730;border:1px solid #2e406d;border-radius:12px;padding:16px;}
.status{font-weight:700;color:#8ef0a7;}
.warning{color:#ffd479;}
.failed{color:#ff8c8c;}
</style>
</head>
<body>
<header>
<h1>PROSPECTOR-ATLAS — FASE 12 — API LAYER</h1>
<p>Status final: <span class='status'>$status</span></p>
</header>
<main>
<section>
<div class='grid'>
<div class='card'><h3>Arquivos criados</h3><p>$($Script:CreatedFiles.Count)</p></div>
<div class='card'><h3>Arquivos atualizados</h3><p>$($Script:UpdatedFiles.Count)</p></div>
<div class='card'><h3>Pastas criadas</h3><p>$($Script:CreatedDirectories.Count)</p></div>
<div class='card'><h3>Tempo</h3><p>${duration}s</p></div>
</div>
</section>
<section><h2>Validações</h2><ul>$validationHtml</ul></section>
<section><h2>Ferramentas</h2>$toolHtml</section>
<section><h2>Hashes SHA-256</h2><table><thead><tr><th>Arquivo</th><th>Hash</th></tr></thead><tbody>$hashHtml</tbody></table></section>
<section><h2>Árvore de diretórios</h2><pre>$([System.Web.HttpUtility]::HtmlEncode($tree))</pre></section>
<section><h2>Resumo executivo</h2><p>A geração da camada API foi concluída com status $status.</p></section>
</main>
</body>
</html>
"@
    Write-FileFromContent -Path $reportPath -Content $html
    $Script:ReportFile = $reportPath
}

function Invoke-Rollback {
    param([Parameter(Mandatory = $true)][string]$TargetRoot)
    $manifestPath = Join-Path $TargetRoot 'phase-12-manifest.json'
    if (-not (Test-Path -LiteralPath $manifestPath)) {
        Write-Log -Level 'ERROR' -Message 'Manifest not found for rollback.'
        return
    }
    $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
    foreach ($file in $manifest.arquivosCriados) {
        if (Test-Path -LiteralPath $file) {
            if ($PSCmdlet.ShouldProcess($file, 'Delete generated file')) {
                Remove-Item -LiteralPath $file -Force
            }
            Write-Log -Level 'OK' -Message ("Removed file: {0}" -f $file)
        }
    }
    foreach ($directory in ($manifest.diretoriosCriados | Sort-Object Length -Descending)) {
        if (Test-Path -LiteralPath $directory) {
            $children = Get-ChildItem -LiteralPath $directory -Force
            if ($children.Count -eq 0) {
                if ($PSCmdlet.ShouldProcess($directory, 'Delete empty directory')) {
                    Remove-Item -LiteralPath $directory -Force
                }
                Write-Log -Level 'OK' -Message ("Removed directory: {0}" -f $directory)
            }
        }
    }
}

Write-Header
$root = Resolve-AbsolutePath -BasePath $ProjectRoot
Write-Log -Level 'INFO' -Message ("Project root: {0}" -f $root)

if ($Rollback) {
    Invoke-Rollback -TargetRoot $root
    exit 0
}

Write-ApiFiles -TargetRoot $root
Test-GeneratedFiles -TargetRoot $root

$toolResults = @()
if ($RunValidation) {
    $toolResults = Invoke-ExternalValidation -TargetRoot $root
}

Write-Manifest -TargetRoot $root -ToolResults $toolResults
if (-not $SkipHtmlReport) {
    Write-HtmlReport -TargetRoot $root -ToolResults $toolResults
}

$status = if ($Script:ValidationFindings.Count -gt 0) { 'WARNING' } else { 'SUCCESS' }
$elapsed = [Math]::Round(((Get-Date) - $Script:StartedAt).TotalSeconds, 2)

Write-Host ''
Write-Host '===================================================='
Write-Host 'FASE 12 — API LAYER'
Write-Host '===================================================='
Write-Host ("Arquivos criados: {0}" -f $Script:CreatedFiles.Count)
Write-Host ("Arquivos atualizados: {0}" -f $Script:UpdatedFiles.Count)
Write-Host ("Pastas criadas: {0}" -f $Script:CreatedDirectories.Count)
Write-Host ("Tempo: {0}s" -f $elapsed)
Write-Host ("Manifest: {0}" -f $Script:ManifestFile)
Write-Host ("Relatório HTML: {0}" -f $Script:ReportFile)
Write-Host ("Validação: {0}" -f $Script:ValidationFindings.Count)
Write-Host ("Status: {0}" -f $status)
Write-Host '===================================================='
