default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "App.xcworkspace", scheme: "App")
    upload_to_testflight
  end

  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "App.xcworkspace", scheme: "App")
    upload_to_app_store
  end
end
